// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-1J8Na26KQ3NCzLn1N4EDlt7bMRbYePQ',
    appId: '1:951075362845:android:84b75deedb4bd923c98ef4',
    messagingSenderId: '951075362845',
    projectId: 'workshopapp-76bdd',
    storageBucket: 'workshopapp-76bdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCRkjiruIk_OG27NiqOPtyPX7Pl2eHfsM',
    appId: '1:951075362845:ios:18cfa78386d801cec98ef4',
    messagingSenderId: '951075362845',
    projectId: 'workshopapp-76bdd',
    storageBucket: 'workshopapp-76bdd.appspot.com',
    androidClientId: '951075362845-oidf0471arsm9nse1u0ik16jo52cb8af.apps.googleusercontent.com',
    iosClientId: '951075362845-2hnuod59mc977h1n1vpnrcvtupbviib2.apps.googleusercontent.com',
    iosBundleId: 'com.sariy312024.sariy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB270SbM5wnA1Gkq7KQrGdju03xhqkaUlw',
    appId: '1:951075362845:web:70aba4d07af75022c98ef4',
    messagingSenderId: '951075362845',
    projectId: 'workshopapp-76bdd',
    authDomain: 'workshopapp-76bdd.firebaseapp.com',
    storageBucket: 'workshopapp-76bdd.appspot.com',
    measurementId: 'G-BRKZC5VTRX',
  );

}